// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAki22Ju1GuEJbVrN-henEzVwYERx118Mk',
    appId: '1:651284308896:web:fa4e45f1f9bfcef983bac5',
    messagingSenderId: '651284308896',
    projectId: 'groomly-4b1a1',
    authDomain: 'groomly-4b1a1.firebaseapp.com',
    storageBucket: 'groomly-4b1a1.firebasestorage.app',
    measurementId: 'G-K874CDNWXQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDReD8HgMdVveGGdO1Q56EscbTBCocHptE',
    appId: '1:651284308896:android:cd472a2c6991b9bd83bac5',
    messagingSenderId: '651284308896',
    projectId: 'groomly-4b1a1',
    storageBucket: 'groomly-4b1a1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3luemxQzipb3zllS-LJTmW-AiTurySPU',
    appId: '1:651284308896:ios:c7e3544e4f6b9e1e83bac5',
    messagingSenderId: '651284308896',
    projectId: 'groomly-4b1a1',
    storageBucket: 'groomly-4b1a1.firebasestorage.app',
    iosBundleId: 'com.example.groomlyes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3luemxQzipb3zllS-LJTmW-AiTurySPU',
    appId: '1:651284308896:ios:c7e3544e4f6b9e1e83bac5',
    messagingSenderId: '651284308896',
    projectId: 'groomly-4b1a1',
    storageBucket: 'groomly-4b1a1.firebasestorage.app',
    iosBundleId: 'com.example.groomlyes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAki22Ju1GuEJbVrN-henEzVwYERx118Mk',
    appId: '1:651284308896:web:684cbc7f3f33fc5083bac5',
    messagingSenderId: '651284308896',
    projectId: 'groomly-4b1a1',
    authDomain: 'groomly-4b1a1.firebaseapp.com',
    storageBucket: 'groomly-4b1a1.firebasestorage.app',
    measurementId: 'G-LRP0WX61FQ',
  );
}
